# Generated by Django 5.1 on 2024-08-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='estimated_time',
            field=models.PositiveIntegerField(help_text='In minutes'),
        ),
    ]
