# Generated by Django 5.1 on 2024-09-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_timeallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeallocation',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
